; Generated by cpp-nes-6502
; --------------------------

.segment "HEADER"
  .byte $4E, $45, $53, $1A  ; 'NES' + MS-DOS EOF
  .byte $02                  ; PRG-ROM size (2 x 16KB)
  .byte $01                  ; CHR-ROM size (1 x 8KB)
  .byte $00                  ; Mapper low / mirroring
  .byte $00                  ; Mapper high
  .byte $00, $00, $00, $00, $00, $00, $00, $00  ; padding
; Header is total 16 bytes.

.segment "CODE"

; Auto-collected constants
playerX = $10
playerY = $11
buttons = $12
buttonsPrev = $13
buttonsPressed = $14
buttonsReleased = $15
PPUCTRL = $2000
PPUMASK = $2001
PPUSTATUS = $2002
PPUADDR = $2006
PPUDATA = $2007
JOY1 = $4016

.proc reset_handler
  SEI
  CLD
  LDA PPUMASK ; $2001
  AND #$E7
  ORA #$00
  STA PPUMASK ; $2001 ; enable rendereing
  LDX #$40
  STX $4017
  LDX #$FF
  TXS
  INX
  STX PPUCTRL ; $2000
  STX PPUMASK ; $2001
  STX $4010
@vblank0:
  LDA PPUSTATUS ; $2002
  BPL @vblank0
@vblank1:
  LDA PPUSTATUS ; $2002
  BPL @vblank1
  LDA PPUMASK ; $2001
  AND #$FF
  ORA #$18
  STA PPUMASK ; $2001 ; disable rendereing
  LDA PPUSTATUS ; $2002
  LDA #$3F
  STA PPUADDR ; $2006
  LDA #$00
  STA PPUADDR ; $2006
  LDX #$00
@loadPalLoop0:
  LDA PaletteData,X
  STA PPUDATA ; $2007
  INX
  CPX #$20
  BNE @loadPalLoop0
  LDA #$1E
  STA PPUMASK ; $2001
  LDA #$00
  STA $16 ; colorIndex
  LDA #$78
  STA playerX ; $10
  LDA #$64
  STA playerY ; $11
  LDA #$80
  STA PPUCTRL ; $2000
  JMP main
.endproc ;reset_handler

.proc nmi_handler
  JSR readInput
  JSR updatePlayer1
  RTI
.endproc ;nmi_handler

.proc main
forever:
  JMP forever
.endproc ;main

.proc readInput
; save previous
  LDA buttons ; $12
  STA buttonsPrev ; $13
; strobe
  LDA #$01
  STA JOY1 ; $4016
  LDA #$00
  STA JOY1 ; $4016
; read 8 buttons
  LDX #$08
  LDA #$00
@readButtonStates0:
  LDA JOY1 ; $4016
  LSR A
  ROL buttons ; $12
  DEX
  BNE @readButtonStates0
; buttonsPressed = current & (~previous)
  LDA buttonsPrev ; $13
  EOR #$FF
  AND buttons ; $12
  STA buttonsPressed ; $14
; buttonsReleased = previous & (~current)
  LDA buttons ; $12
  EOR #$FF
  AND buttonsPrev ; $13
  STA buttonsReleased ; $15
  RTS
.endproc ;readInput

.proc updatePlayer1
  LDA buttons ; $12
  AND #$08
  BEQ @not_up
@not_up:
  LDA buttons ; $12
  AND #$04
  BEQ @not_down
@not_down:
  LDA buttons ; $12
  AND #$02
  BEQ @not_left
  DEC playerX ; $10
@not_left:
  LDA buttons ; $12
  AND #$01
  BEQ @not_right
  INC playerX ; $10
@not_right:
  LDA buttons ; $12
  AND #$80
  BEQ @not_a
@not_a:
  LDA buttons ; $12
  AND #$40
  BEQ @not_b
@not_b:
  LDA buttons ; $12
  AND #$20
  BEQ @not_select
@not_select:
  LDA buttons ; $12
  AND #$10
  BEQ @not_start
@not_start:
  RTS
.endproc ;updatePlayer1

PaletteData:
  .byte $0F,$31,$01,$30 ;Background palette 0
  .byte $0F,$02,$0A,$07 ;Background palette 1
  .byte $0F,$31,$0B,$07 ;Background palette 2
  .byte $0F,$08,$00,$07 ;Background palette 3
  .byte $0F,$00,$10,$30 ;Foreground palette 0
  .byte $0F,$39,$1C,$05 ;Foreground palette 1
  .byte $0F,$3B,$02,$05 ;Foreground palette 2
  .byte $0F,$13,$26,$05 ;Foreground palette 3

.segment "OAM"
OAMBuffer:
.res 256

.segment "VECTORS"
  .word nmi_handler ; NMI
  .word reset_handler ; RESET
  .word 0 ; IRQ

.segment "CHARS"
; WARNING: No CHR data loaded
.res 8192 ; Reserving 8192 bytes of blank space

.segment "STARTUP"
