#include <catch2/catch_test_macros.hpp>

#include "asmemitter.hpp"
#include <sstream>

namespace {
  std::string expected();
}

TEST_CASE("AsmEmitter generates expected output", "[asmemitter]")
{
  using namespace cppnes;
  MemoryMap mem;
  ZpAddress playerX = mem.zeroPage.alloc("playerX");
  ZpAddress playerY = mem.zeroPage.alloc("playerY");

  Program prg(mem);

  Label waitVBlank("waitVBlank");
  Label vblankLoop("vblankLoop");

  Subroutine &reset = prg.addSubroutine("reset_handler");
  prg.setResetVector(reset);
  reset.sei()
    .cld()
    .ldx(Immediate{ 0xFF })
    .txs()
    .lda(Immediate{ 0x00 })
    .sta(ZeroPage{ playerX })
    .sta(ZeroPage{ playerY })
    .label(waitVBlank)
    .lda(Absolute{ AbsAddress{0x2002} })
    .bpl(vblankLoop)
    .jmp(Absolute{ AbsAddress{0x8000} });

  Subroutine &nmi = prg.addSubroutine("nmi_handler");
  nmi.rti();
  prg.setNMIVector(nmi);

  Subroutine &irq = prg.addSubroutine("irq_handler");
  irq.rti();
  prg.setIRQVector(irq);

  Rom rom;
  rom.setProgram(prg);

  std::stringstream ss;
  AsmEmitter emitter;
  emitter.emitInesHeader(rom, ss);
  std::string generated = ss.str();
  ss = {};
  emitter.emitPrgAsm(prg, ss);
  generated += ss.str();
  REQUIRE(generated == expected());
}

namespace {

  std::string expected() {
    std::string str = R"(
; Generated by cpp-nes-6502
; --------------------------

.segment "HEADER"
    .byte $4E, $45, $53, $1A  ; "NES" + EOF
    .byte $02                  ; 2x 16KB PRG banks
    .byte $01                  ; 1x 8KB CHR bank
    .byte $00                  ; mapper 0, horizontal mirroring
    .byte $00

.segment "CODE"

Reset:
    SEI
    CLD
    LDX #$FF
    TXS
    LDA #$00
    STA $00             ; playerX
    STA $01             ; playerY
waitVBlank:
    LDA $2002
    BPL vblankLoop      ; warning: forward ref — label not yet defined
    JMP $8000

.segment "VECTORS"
    .word 0             ; NMI   (not set)
    .word Reset         ; RESET
    .word 0             ; IRQ   (not set)
)";
    return str;
  };

}